/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
/* @ts-nocheck */

import { AddressResolverFunction } from '@dappql/async'
import { PublicClient, WalletClient } from 'viem'

import * as ToDo from './ToDo.js'

export type SDK = {
		ToDo: ToDo.SDK
}

export default function createSdk(publicClient?: PublicClient, walletClient?: WalletClient, addressResolver?: AddressResolverFunction): SDK {
  return {
		ToDo: ToDo.toSdk(publicClient, walletClient, addressResolver),
  }
}
