import { existsSync, readFileSync } from 'fs'
import { join } from 'path'
import { fileURLToPath } from 'url'

import { summarizeContract } from './contracts.js'
import type { ProjectContext } from './types.js'

export type ResourceDescriptor = {
  uri: string
  name: string
  description: string
  mimeType: string
}

// Bundled by scripts/copy-library-reference.mjs at build time. Lives at
// <package>/assets/library-reference.md, one level up from dist/resources.js
// after compilation.
const LIBRARY_REFERENCE_PATH = (() => {
  try {
    return fileURLToPath(new URL('../assets/library-reference.md', import.meta.url))
  } catch {
    return null
  }
})()

function loadLibraryReference(): string | null {
  if (!LIBRARY_REFERENCE_PATH) return null
  try {
    return readFileSync(LIBRARY_REFERENCE_PATH, 'utf8')
  } catch {
    return null
  }
}

export function listResources(ctx: ProjectContext): ResourceDescriptor[] {
  const out: ResourceDescriptor[] = []
  const agentsPath = join(ctx.root, 'AGENTS.md')
  if (existsSync(agentsPath)) {
    out.push({
      uri: 'dappql://project/AGENTS.md',
      name: 'Project AGENTS.md',
      description: 'The project-specific agent guide generated by dappql (contracts, patterns, non-negotiables).',
      mimeType: 'text/markdown',
    })
  }
  for (const name of Object.keys(ctx.config.contracts)) {
    out.push({
      uri: `dappql://contracts/${name}`,
      name: `Contract: ${name}`,
      description: `ABI and method summary for ${name}.`,
      mimeType: 'application/json',
    })
  }
  out.push({
    uri: 'dappql://project/config',
    name: 'dapp.config.js (summary)',
    description: 'Normalized view of the project config — chain, target path, flags, contract names.',
    mimeType: 'application/json',
  })
  out.push({
    uri: 'dappql://docs/library',
    name: 'DappQL library reference',
    description:
      'Canonical reference for the DappQL toolchain: React hooks, provider options, non-React runtime, SDK generation, codegen behavior, and non-negotiables for AI agents. Read this once to understand what\'s available beyond the project-specific AGENTS.md.',
    mimeType: 'text/markdown',
  })
  return out
}

export function readResource(uri: string, ctx: ProjectContext): { mimeType: string; text: string } {
  if (uri === 'dappql://project/AGENTS.md') {
    const path = join(ctx.root, 'AGENTS.md')
    if (!existsSync(path)) throw new Error('AGENTS.md not found in project root')
    return { mimeType: 'text/markdown', text: readFileSync(path, 'utf8') }
  }

  if (uri === 'dappql://project/config') {
    const body = {
      configPath: ctx.configPath,
      root: ctx.root,
      chainId: ctx.chainId ?? null,
      targetPath: ctx.config.targetPath,
      isSdk: Boolean(ctx.config.isSdk),
      isModule: Boolean(ctx.config.isModule),
      contracts: Object.keys(ctx.config.contracts),
    }
    return { mimeType: 'application/json', text: JSON.stringify(body, null, 2) }
  }

  const contractMatch = uri.match(/^dappql:\/\/contracts\/([^\/]+)$/)
  if (contractMatch) {
    const name = contractMatch[1]
    const contract = ctx.config.contracts[name]
    if (!contract) throw new Error(`Contract not found: ${name}`)
    const summary = summarizeContract(name, contract)
    const body = { ...summary, abi: contract.abi ?? null }
    return { mimeType: 'application/json', text: JSON.stringify(body, null, 2) }
  }

  if (uri === 'dappql://docs/library') {
    const text = loadLibraryReference()
    if (text) return { mimeType: 'text/markdown', text }
    return {
      mimeType: 'text/markdown',
      text:
        '# DappQL library reference\n\nNot bundled with this build.\n\n' +
        'See https://github.com/dappql/monorepo/blob/main/AGENTS.md for the canonical reference.',
    }
  }

  throw new Error(`Unknown resource URI: ${uri}`)
}
